<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK90J5Kj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK90J5Kj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK90J5Kj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK90J5Kj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK90J5Kj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K90J5Kj',
    'container.build_id' => 'fe17de98',
    'container.build_time' => 1652464770,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK90J5Kj');
