<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Services extends \App\Entity\Services implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'ids', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'formule', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'sejours', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'activite', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'hotels'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'ids', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'formule', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'sejours', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'activite', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Services' . "\0" . 'hotels'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Services $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIds(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIds();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIds', []);

        return parent::getIds();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormule', []);

        return parent::getFormule();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormule(string $formule): \App\Entity\Services
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormule', [$formule]);

        return parent::setFormule($formule);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Services
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getSejours(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSejours', []);

        return parent::getSejours();
    }

    /**
     * {@inheritDoc}
     */
    public function setSejours(?string $sejours): \App\Entity\Services
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSejours', [$sejours]);

        return parent::setSejours($sejours);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivite', []);

        return parent::getActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivite(string $activite): \App\Entity\Services
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivite', [$activite]);

        return parent::setActivite($activite);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(string $etat): \App\Entity\Services
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotels(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotels', []);

        return parent::getHotels();
    }

    /**
     * {@inheritDoc}
     */
    public function addHotel(\App\Entity\Hotels $hotel): \App\Entity\Services
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHotel', [$hotel]);

        return parent::addHotel($hotel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHotel(\App\Entity\Hotels $hotel): \App\Entity\Services
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHotel', [$hotel]);

        return parent::removeHotel($hotel);
    }

}
